"""add holdings table and subscriber portfolio_token

Revision ID: 0fa9c0813cba
Revises: 8d32ee993b5d
Create Date: 2026-06-30 22:58:54.422278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa9c0813cba'
down_revision: Union[str, None] = '8d32ee993b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('sealed_product_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(card_id IS NOT NULL) != (sealed_product_id IS NOT NULL)', name='holding_exactly_one_item'),
    sa.CheckConstraint('purchase_price >= 0', name='holding_purchase_price_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='holding_quantity_positive'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['sealed_product_id'], ['sealed_products.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_card_id'), 'holdings', ['card_id'], unique=False)
    op.create_index(op.f('ix_holdings_sealed_product_id'), 'holdings', ['sealed_product_id'], unique=False)
    op.create_index(op.f('ix_holdings_subscriber_id'), 'holdings', ['subscriber_id'], unique=False)
    op.add_column('subscribers', sa.Column('portfolio_token', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_subscribers_portfolio_token'), 'subscribers', ['portfolio_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_portfolio_token'), table_name='subscribers')
    op.drop_column('subscribers', 'portfolio_token')
    op.drop_index(op.f('ix_holdings_subscriber_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_sealed_product_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_card_id'), table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###
