"""add subscribers table

Revision ID: 8d32ee993b5d
Revises: cfcfdb4756c8
Create Date: 2026-06-30 22:21:07.909640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d32ee993b5d'
down_revision: Union[str, None] = 'cfcfdb4756c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confirm_token', sa.String(length=64), nullable=True),
    sa.Column('confirm_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("cadence IN ('daily', 'weekly')", name='subscriber_cadence_valid'),
    sa.CheckConstraint("channel IN ('email', 'sms')", name='subscriber_channel_valid'),
    sa.CheckConstraint("status IN ('pending_verification', 'active', 'unsubscribed')", name='subscriber_status_valid'),
    sa.CheckConstraint('(email IS NOT NULL) != (phone IS NOT NULL)', name='subscriber_exactly_one_contact'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_confirm_token'), 'subscribers', ['confirm_token'], unique=True)
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_subscribers_phone'), 'subscribers', ['phone'], unique=True)
    op.create_index(op.f('ix_subscribers_status'), 'subscribers', ['status'], unique=False)
    op.create_index(op.f('ix_subscribers_unsubscribe_token'), 'subscribers', ['unsubscribe_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_unsubscribe_token'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_status'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_phone'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_confirm_token'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
