"""phase 0 schema

Revision ID: a2f13ca2720a
Revises: 
Create Date: 2026-06-30 21:43:19.881628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f13ca2720a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('set_name', sa.String(length=255), nullable=False),
    sa.Column('set_code', sa.String(length=32), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('rarity', sa.String(length=64), nullable=True),
    sa.Column('tcgplayer_product_id', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('ix_cards_tcgplayer_product_id'), 'cards', ['tcgplayer_product_id'], unique=True)
    op.create_table('news_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("url <> ''", name='news_item_url_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_table('sealed_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('set_name', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=64), nullable=True),
    sa.Column('tcgplayer_product_id', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sealed_products_name'), 'sealed_products', ['name'], unique=False)
    op.create_index(op.f('ix_sealed_products_tcgplayer_product_id'), 'sealed_products', ['tcgplayer_product_id'], unique=True)
    op.create_table('price_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('sealed_product_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('price_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_mid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(card_id IS NOT NULL) != (sealed_product_id IS NOT NULL)', name='price_snapshot_exactly_one_item'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['sealed_product_id'], ['sealed_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_captured_at'), 'price_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_card_id'), 'price_snapshots', ['card_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_sealed_product_id'), 'price_snapshots', ['sealed_product_id'], unique=False)
    op.create_table('restock_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sealed_product_id', sa.UUID(), nullable=True),
    sa.Column('product_name_raw', sa.String(length=255), nullable=False),
    sa.Column('retailer', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sealed_product_id'], ['sealed_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restock_events_detected_at'), 'restock_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_restock_events_sealed_product_id'), 'restock_events', ['sealed_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restock_events_sealed_product_id'), table_name='restock_events')
    op.drop_index(op.f('ix_restock_events_detected_at'), table_name='restock_events')
    op.drop_table('restock_events')
    op.drop_index(op.f('ix_price_snapshots_sealed_product_id'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_card_id'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_captured_at'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_sealed_products_tcgplayer_product_id'), table_name='sealed_products')
    op.drop_index(op.f('ix_sealed_products_name'), table_name='sealed_products')
    op.drop_table('sealed_products')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_cards_tcgplayer_product_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
