"""add alert_rules table

Revision ID: cf8d678f8a2c
Revises: 0fa9c0813cba
Create Date: 2026-06-30 23:31:44.151635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8d678f8a2c'
down_revision: Union[str, None] = '0fa9c0813cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('sealed_product_id', sa.UUID(), nullable=True),
    sa.Column('watch_text', sa.String(length=255), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('window_hours', sa.Integer(), nullable=False),
    sa.Column('is_armed', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rule_type IN ('price_above', 'price_below', 'pct_move', 'restock')", name='alert_rule_type_valid'),
    sa.CheckConstraint('card_id IS NOT NULL OR sealed_product_id IS NOT NULL OR watch_text IS NOT NULL', name='alert_rule_has_target'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['sealed_product_id'], ['sealed_products.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_card_id'), 'alert_rules', ['card_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_sealed_product_id'), 'alert_rules', ['sealed_product_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_subscriber_id'), 'alert_rules', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_rules_subscriber_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_sealed_product_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_card_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
